---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: development
  name: guest
spec:
  memberOf: [rbac-plugin-team, servicenow-plugin-team]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: development
  name: rbac-plugin-team
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: development
  name: servicenow-plugin-team
spec:
  type: team
  children: []
